version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper 
    ports:
      - "2181:2181"
    
   
      
      
    
  
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.23.238.156
      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "Test5:1:1,Test4:1:1"
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1
      
      
     
      
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
